Shooter tuning stuff
denbot/2024CompetitionSeason pull request #40
Opened 2024-03-12 23:11 UTC by Stubbynarwhal

2024-03-14 01:26 UTC, centiwati requested changes

2024-03-14 01:26 UTC, centiwati commented on src/main/java/frc/robot/RobotContainer.java
> +  private final PrepCommand ampShoot = new PrepCommand(shooterSubsystem, 59.6, 0.25); //TODO Tune for actual angles
We might want to change this... I've noticed it's not super consistent. Either slower speed or different angle, or both.

2024-03-14 01:26 UTC, centiwati commented on src/main/java/frc/robot/RobotContainer.java
> +    return autoChooser.getSelected();
We want to comment this out I believe. @awfulcarpet You should work on figuring out why this doesn't work and how we should do it instead.

2024-03-14 01:26 UTC, centiwati commented on src/main/java/frc/robot/commands/ShootCommand.java
> +  private double speed = 0.2; // TODO Change to intake motor speed (in rotations per second)
This isn't rotations per second but percentage of power.

2024-03-14 01:26 UTC, centiwati commented on src/main/java/frc/robot/subsystems/Intake.java
> +                if (timer.hasElapsed(0.15) && ! noteHitShooter) { // TODO: tune this value. This timer starts when the note hits the last sensor, and this value will make the indexer go backwards for
This timer needs to be tuned a bit. @GucciBanana11 Decrease the value a bit.

2024-03-14 01:26 UTC, centiwati commented on src/main/java/frc/robot/subsystems/Intake.java
> +                if (timer.hasElapsed(0.15) && noteHitShooter) { // TODO: tune this value. This timer starts when the note hits the shooter wheels, and this value stops the intaking process when the t
Increase this time by a bit @GucciBanana11

2024-03-15 19:19 UTC, awfulcarpet commented on src/main/java/frc/robot/RobotContainer.java
> +    return autoChooser.getSelected();
is fixed in #42

2024-03-16 19:24 UTC, closed without merging

2024-03-16 19:24 UTC, GucciBanana11 commented
To be fixed with new PR