Added swerve configuration using Phoenix Tuner X tool
denbot/2024CompetitionSeason pull request #7
Opened 2024-02-15 01:11 UTC by Stubbynarwhal

We used Phoenix Tuner X and changed all the CAN IDs so they made sense, and then went through the steps to configure the swerve. Justin helped me and Elliott (basically did it for us and explained the process) of moving the code into our repo. :) We'll need to fix some things in the future but its a good start 👍

2024-02-17 20:37 UTC, Jnesselr requested changes
Only requesting changes for moving the file under the `subsystems` package and for the `a()` and `b()` buttons being overloaded.

2024-02-17 20:37 UTC, Jnesselr commented on src/main/java/frc/robot/CommandSwerveDrivetrain.java
> +public class CommandSwerveDrivetrain extends SwerveDrivetrain implements Subsystem {
This should be moved to the subsystems directory/package.

2024-02-17 20:37 UTC, Jnesselr commented on src/main/java/frc/robot/RobotContainer.java
> +  private double MaxAngularRate = 1.5 * Math.PI; // 3/4 of a rotation per second max angular velocity
Variable names don't match our convention. Should be camel case. They're technically constants here but let's leave them as variables in case we want to modify them on the fly later.

2024-02-17 20:37 UTC, Jnesselr commented on src/main/java/frc/robot/RobotContainer.java
> +    m_driverController.a().whileTrue(drivetrain.applyRequest(() -> brake));
`a()` is amp command above on true but while true it does a brake here. We should remap the brake to something else or remove it altogether depending on what our driver wants.

2024-02-17 20:37 UTC, Jnesselr commented on src/main/java/frc/robot/RobotContainer.java
> +    m_driverController.b().whileTrue(drivetrain
`b()` also conflicts here, though I don't fully understand what this code is supposed to do. It seems to be a way to hold a button and then set the wheels in that direction while the button is being held. Not sure how useful it will be.

2024-02-17 20:37 UTC, Jnesselr commented on src/main/java/frc/robot/RobotContainer.java
> +  private final Telemetry logger = new Telemetry(MaxSpeed);
`logger` is probably a bad name here. Maybe `telemetry`?

2024-02-17 20:37 UTC, Jnesselr commented on src/main/java/frc/robot/RobotContainer.java
> +    m_driverController.leftBumper().onTrue(drivetrain.runOnce(() -> drivetrain.seedFieldRelative()));
Maybe this should be the start button? Very driver dependent for this.

2024-02-17 20:37 UTC, Jnesselr commented on src/main/java/frc/robot/Telemetry.java
> +    private final double MaxSpeed;
This is final, but we should still use camel case.

2024-02-17 20:37 UTC, Jnesselr commented on src/main/java/frc/robot/Telemetry.java
> +    private final NetworkTableInstance inst = NetworkTableInstance.getDefault();
`inst` is probably not the best name for this. `inst` of what? Honestly even the full version of `networkTableInstance` would be better than this.

2024-02-17 20:37 UTC, Jnesselr commented on src/main/java/frc/robot/Telemetry.java
> +    private final StringPublisher fieldTypePub = table.getStringTopic(".type").publish();
I'm unsure why type is prefixed with a `.`. Is it hidden? Is `type` a reserved name so we had to use `.type`? I don't think this is anything to change but I'm curious now.

2024-02-17 20:37 UTC, Jnesselr commented on src/main/java/frc/robot/Telemetry.java
> +    private Pose2d m_lastPose = new Pose2d();
Everywhere they use `m_` names, do we want to remove that to keep our convention?

2024-02-17 20:37 UTC, Jnesselr commented on src/main/java/frc/robot/generated/TunerConstants.java
> +    private static final String kCANbusName = "Default Name";
This needs to be the CANivore name or serial number. See https://api.ctr-electronics.com/phoenix6/release/java/com/ctre/phoenix6/mechanisms/swerve/SwerveDrivetrainConstants.html#CANbusName

2024-02-17 20:37 UTC, Jnesselr commented on src/main/java/frc/robot/generated/TunerConstants.java
> +    public static final double kSpeedAt12VoltsMps = 6.21;
Add a TODO to tune this.

2024-02-17 20:37 UTC, Jnesselr commented on src/main/java/frc/robot/generated/TunerConstants.java
> +    private static final ClosedLoopOutputType driveClosedLoopOutput = ClosedLoopOutputType.Voltage;
TODO look into TorqueCurrentFOC to see if we can get higher motor speeds. I'd add the TODO as a comment and start to research it.

2024-02-17 22:14 UTC, AcharMRSO commented on src/main/java/frc/robot/RobotContainer.java
> +    m_driverController.leftBumper().onTrue(drivetrain.runOnce(() -> drivetrain.seedFieldRelative()));
leaving as is for now

2024-02-17 22:55 UTC, Jnesselr commented on src/main/java/frc/robot/CommandSwerveDrivetrain.java
> +public class CommandSwerveDrivetrain extends SwerveDrivetrain implements Subsystem {
Also we should rename this to `SwerveSubsystem`

2024-02-20 08:02 UTC, Jnesselr approved these changes
All remaining comments are questions / minor issues.

2024-02-20 17:29 UTC, centiwati approved these changes

2024-02-20 17:29 UTC, merged