Updated device IDs for intake and shooter
denbot/2024CompetitionSeason pull request #8
Opened 2024-02-19 16:59 UTC by GucciBanana11

Wrist, intake and shooter motors set IDs

2024-02-19 17:02 UTC, Jnesselr requested changes

2024-02-19 17:02 UTC, Jnesselr commented on src/main/java/frc/robot/subsystems/Shooter.java
> +  private final TalonFX rightShootMotor = new TalonFX(13); // TODO: Set to right motor device Id
These TODOs are no longer valid.

2024-02-19 17:50 UTC, Jnesselr approved these changes

2024-02-20 15:44 UTC, Charles54321 approved these changes
Changes to intake subsystem code present themselves as adequate.

2024-02-20 15:45 UTC, merged

2024-02-20 15:46 UTC, Charles54321 commented
shut up

On Tue, Feb 20, 2024 at 8:45 AM GucciBanana11 ***@***.***>
wrote:

> Merged #8
> <https://urldefense.com/v3/__https://github.com/Anglebotics/2024CompetitionSeason/pull/8__;!!I5wY4Ip2iQ-G!9o8ltu-OXNJ4tn8fyP2KXdAGvPWC65JKcSgyLrAwzvrpZVbY7OxArNiG-Uar8jVW6TLkv8fh3dmGKAvRHDpmvERJwre5uw$>
> into main.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.com/v3/__https://github.com/Anglebotics/2024CompetitionSeason/pull/8*event-11863743073__;Iw!!I5wY4Ip2iQ-G!9o8ltu-OXNJ4tn8fyP2KXdAGvPWC65JKcSgyLrAwzvrpZVbY7OxArNiG-Uar8jVW6TLkv8fh3dmGKAvRHDpmvEQlsmdwZQ$>,
> or unsubscribe
> <https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/BDAW2PGMQTWQTBNLYC5OYGDYUTAKHAVCNFSM6AAAAABDPZK2PCVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJRHA3DGNZUGMYDOMY__;!!I5wY4Ip2iQ-G!9o8ltu-OXNJ4tn8fyP2KXdAGvPWC65JKcSgyLrAwzvrpZVbY7OxArNiG-Uar8jVW6TLkv8fh3dmGKAvRHDpmvERixh0rHw$>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***
> com>
>